### ISSUE TITLE
Add license information for the project

### ISSUE THREAD

**Issue by mghansen256** [nelsond/sirah-matisse-commander#1]
Would be nice if you could add some explicit licensing information to this project. Even if you want to release it as "public-domain", you could state [CC-0](https://github.com/topics/cc0) as a license to assert that officially.

**Comment by nelsond** [comment]
The project has been released under the MIT license, as mentioned in the `setup.py`.

https://github.com/nelsond/sirah-matisse-commander/blob/362648b507156f15c344bcc6e1dede693b677010/setup.py#L28

I have now also added an explicit `LICENSE` file with the MIT license information, hope that helps.

**Comment by mghansen256** [comment]
Thanks! That makes it easier to spot it!
